config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy]

  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  
  has_one_attached :image
  belongs_to :user
  
  validates :body, presence: true, length: { maximum: 500 }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
    
  end  
  
  def about
    
  end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.image.attach(params[:post][:image])
    @post.save
    redirect_to post_path(@post.id)
  end

  def index
    @posts = Post.includes(:user).all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post.id)
  end
  
  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to user_path(current_user)
  end  

  private

   def post_params
     params.require(:post).permit(:title, :body, :image)
   end

   def is_matching_login_user
     post = Post.find(params[:id])
     unless post.user_id == current_user.id
       redirect_to posts_path
     end
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end


  private

  def user_params
    params.require(:user).permit(:name, :age, :gender, :introduction, :profile_image)
  end
  
  def is_matching_login_user
     user = User.find(params[:id])
     unless user.id == current_user.id
       redirect_to user_path(current_user.id)
     end  
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<body>
  <main>
    <%= stylesheet_link_tag 'about' %>
      <div class="container-fluid my-5 back-image">
        <div class="row">
          <div class="mx-auto col-12 col-sm-10 col-lg-8 col-xl-5">
            <%= stylesheet_link_tag 'about' %>
            <h1 class='text-center'>このサイトについて</h1>
              <p class="text-center">
                  ダイエットに関する情報交換<br>
                  モチベーションを保つためのコミュニケーションの場
              </p>
          </div>
        </div>
      </div>
  </main>
</body>    

app/views/homes/top.html.erb
<body>
  <main>
   <%= stylesheet_link_tag 'top' %>
    <div class="container-fluid back-image">
      <div class="row">
        <div class="mx-auto col-12 col-sm-10 col-lg-8 col-xl-5">

          <h1 class='mt-5 text-center'>Diet x Health</h1>

            <%= link_to new_user_session_path, class: 'btn btn-info btn-sm btn-block mt-5 mb-3 sign_in' do %>
              ログイン
            <% end %>
            <%= link_to new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' do %>
              新規登録
            <% end %>
        </div>
      </div>
   </div>
  </main>
</body>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diet x Health</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/fcc22d5b28.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ffa500;">
       <div class="container">
        <a class="navbar-brand" href="/">Diet x Health</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-taeget="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">

          <% if user_signed_in? %>
            <li class="nav-item">
             <%= link_to root_path, class: 'nav-link text-dark' do %>
               <i class="fa-solid fa-house"></i> Home
             <% end %>
            </li>
            <li class="nav-item">
             <%= link_to user_path(current_user), class: 'nav-link text-dark' do %>
               <i class="fa-solid fa-circle-user"></i> マイページ
             <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_post_path, class: 'nav-link text-dark' do %>
               <i class="fa-solid fa-user-pen"></i> 新規投稿
               <% end %>
            </li>
            <li class="nav-item">
             <%= link_to posts_path, class: 'nav-link text-dark' do %>
               <i class="fa-solid fa-file-pen"></i>投稿一覧
             <% end %>
            </li>
            <li class="nav-item">
             <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-dark' do %>
               <i class="fa-solid fa-right-from-bracket"></i> ログアウト
             <% end %>
            </li>
          <% else %>
            <li class="nav-item">
             <%= link_to "/about", class: 'nav-link text-dark' do %>
               <i class="fa-solid fa-dumbbell"></i> About
             <% end %>
            </li>
            <li class="nav-item">
             <%= link_to new_user_registration_path, class: 'nav-link text-dark' do %>
               <i class="fa-solid fa-user-plus"></i> 新規登録
             <% end %>
            </li>
            <li class="nav-item">
             <%= link_to new_user_session_path, class: 'nav-link text-dark' do %>
               <i class="fa-solid fa-right-to-bracket"></i> ログイン
             <% end %>
            </li>
          <% end %>
         </ul>
        </div>
       </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mt-5 mx-auto">
       <h1>投稿編集</h1>
        <%= form_with model: @post, url: post_path(@post.id), method: :patch do |f| %>
         <p>タイトル</p>
          <%= f.text_field :title %>
          
          <p>画像</p>
          <%= f.file_field :image, accept: "image/*" %>

         <p>本文</p>
          <%= f.text_area :body %><br>
  
          <%= f.submit %>
        <% end %>  
        <%= link_to "Show", post_path(@post.id) %> 
         |
        <%= link_to "Back", posts_path %>
      </div> 
    </div>
  </div>

app/views/posts/index.html.erb
<h2 class="mt-5">投稿一覧</h2>
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th>ユーザー名</th>
        <th>タイトル</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <% if post.user.present? && post.user.profile_image.present? %>
            <td><%= link_to image_tag(post.user.profile_image, size: "100x100"), user_path(post.user) %></td>
          <% else %>
            <td><%= link_to image_tag('no_image.jpg', size: "100x100"), user_path(post.user) %></td>
          <% end %>
            <td><%= link_to post.user.name, user_path(post.user) %></td>
            <td><%= link_to post.title, post_path(post.id) %></td>

          <% if post.user == current_user %>
            <td><%= link_to "編集", edit_post_path(post.id), class: 'btn btn-success' %></td>
            <td><%= link_to "削除", post_path(post.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: 'btn btn-danger' %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mt-5 mx-auto">

      <h1>投稿</h1>
        <%= form_with model: @post do |f| %>
          <p>タイトル</p>
          <%= f.text_field :title %>
          
          <p>画像</p>
          <%= f.file_field :image, accept: "image/*" %>
      
          <p>本文</p>
      　   <%= f.text_area :body %>
      
         <%= f.submit %>
      
        <% end %>
    </div>  
  </div>    
</div>  

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2 class ="mt-5">投稿詳細</h2>
        <p>【タイトル】
          <%= @post.title %>
        </p>  
        <p>
          <% if @post.image.attached? %>
            <%= image_tag(@post.image, size: "200x200") %>
          <% else %>
            <p> 画像なし </p>
          <% end %>
        </P>
        <p>【本文】</p>
        <P> <%= @post.body %> </p>
        
        <% if @post.user == current_user %>
          <%= link_to "編集", edit_post_path(@post.id), class: 'btn btn-success' %>
          <%= link_to "削除", @post_path, method: :delete, "data-confirm" => "本当に削除しますか？", class: 'btn btn-danger' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          <h1>プロフィール編集</h1>
            <%= form_with model: @user do |f| %>
              <div class="form-group">
                <label for="inputImage">プロフィール画像</label><br>
                <%= f.file_field :profile_image, placeholder:"プロフィール画像", accept: "image/*" %>
              </div>

              <div class="form-group">
                <label for="inputName">ユーザー名</label><br>
                <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前" %>
              </div>

              <div class="form-group">
                <label for="inputAge">年齢</label><br>
                <%= f.text_field :age, autofocus: true, id:"inputAge", placeholder:"入力しなくてもいいです" %>
              </div>

              <div class="form-group">
                <label for="inputGender">性別</label><br>
                <%= f.text_field :gender, autofocus: true, id:"inputGender", placeholder:"性別" %>
              </div>

              <div class="form-group">
                <label for="inputIntroduction">一言</label><br>
                <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介文" %>"
              </div>

              <%= f.submit '編集', class: 'btn btn-secondary' %>
            <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2 class="mt-5">マイページ</h2>

         <% if @user.profile_image.attached? %>
            <%= image_tag @user.profile_image, size: "100x100" %>
         <% else %>
            <%= image_tag 'no_image.jpg', size: "100x100" %>
         <% end %>

         <table class="table">
           <tbody>
             <tr>
                <th>名前</th>
                <th><%= @user.name %></th>
             </tr>
             <tr>
                <th>年齢</th>
                <th><%= @user.age %></th>
             </tr>
             <tr>
                <th>性別</th>
                <th><%= @user.gender %></th>
             </tr>
             <tr>
                <th>一言</th>
                <th><%= @user.introduction %></th>
             </tr>
            </tbody>
          </table>
          <div class="row">
            <%= link_to edit_user_path(@user.id), class: 'btn btn-outline-info' do %>
              プロフィール編集
            <% end %>
          </div>
      </div>
      <div class= "col-md-8 offset-md-1">
        <h2 class="mt-5">投稿履歴</h2>
        　<table class="table">
            <thead>
              <tr>
                <th></th>
                <th>タイトル</th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @posts.each do |post| %>
                <tr>
                  <td></td>
                  <td><%= link_to post.title, post_path(post.id) %></td>
                <% if post.user == current_user %>
                  <td><%= link_to "編集", edit_post_path(post.id), class: 'btn btn-success' %></td>
                  <td><%= link_to "削除", post_path(post.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: 'btn btn-danger' %></td>
                <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>
</main>